# some more ls aliases
alias sshfsnas='sshfs flieh@192.168.1.46:Public ~/NAS' 
alias sshfsgranite='sshfs flieh@192.168.1.9:/home/flieh ~/GRANITE'
alias sshfseee='sshfs knoppix@192.168.1.5:/home/knoppix ~/EEE'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias li='ls -li'
alias sand='cd ~/sandbox'
alias sdn='shutdown now'
alias sam='cd ~/projects/node/Samuel'
alias gmu='git commit -m "update"'
alias surge-tourn='surge -d droidippy-tournament-2017.surge.sh -p .'
alias wifi='sudo service network-manager restart'
alias webseed="git clone https://github.com/Flieh/webseed.git"
# alias browser-sync="./node_modules/browser-sync/bin/browser-sync.js"
alias proj-sync-to-granite="sudo rsync -avh ~/projects/ sean@192.168.1.9:~/projects --delete"
alias vimess="vim -u ~/projects/vimcode/essential.vim"
alias killcode="killall -9 code"
alias py="python3"
alias rmsand="rm -rf ~/sandbox/*"
alias watchtest="nodemon --exec jasmine"
alias stgrp="set | grep -i"
alias ptst="pytest-3"
alias rs="source ~/dotfiles/.bashrc"
alias oracle-ubuntu='ssh ubuntu@130.61.189.196'
